
import { StockData } from './types';

export const STOCKS: StockData[] = [
  {
    symbol: 'RCL',
    fullName: 'Royal Caribbean Group',
    mainBusiness: "World's second-largest cruise operator, owns Royal Caribbean International, Celebrity, Silversea; fleet 68 ships. The company focuses on large-scale innovation and luxury segments, maintaining a dominant market share in the premium vacation industry.",
    financials: {
      revenue: '$5.14B',
      netProfit: '$1.58B',
      cashFlow: 'Free Cash Flow -$989M',
      period: 'Q3 2025'
    },
    indicators: {
      occupancy: '112%',
      roic: '15.7%',
      roe: '28.4%',
      cashFlow: 'Negative FCF due to ship delivery timing',
      debt: '$20.98B',
      currentRatio: '0.16',
      leverageNote: 'highly leveraged'
    },
    latestDevelopments: [
      'Extended shipbuilding with Meyer Turku to 2036',
      'Icon 5-7 orders and options confirmed'
    ],
    currentPrice: '$304.33'
  },
  {
    symbol: 'MU',
    fullName: 'Micron Technology',
    mainBusiness: "Leading memory chip maker, focus on DRAM, NAND, HBM (High Bandwidth Memory) for AI/data centers. Micron is strategically positioned as a core infrastructure provider for the generative AI revolution.",
    financials: {
      revenue: '$13.64B (driven by HBM)',
      netProfit: '$5.24B',
      cashFlow: 'TTM Op Cash Flow Margin 53.63%',
      period: 'Q ending Nov 2025'
    },
    indicators: {
      margin: '53.63% (Op Cash Flow)',
      roic: '21.73%',
      roe: '18.9%',
      cashFlow: 'Strong Operating Cash Flow generated by HBM premium',
      debt: 'N/A',
      currentRatio: 'N/A',
      buildup: 'deliberate HBM inventory buildup'
    },
    latestDevelopments: [
      'HBM 2026 fully sold out',
      '$20B CapEx planned for FY26'
    ],
    currentPrice: '$327.02'
  },
  {
    symbol: 'LLY',
    fullName: 'Eli Lilly and Company',
    mainBusiness: "Pharma giant, incretin drugs (Mounjaro/Zepbound) dominate revenue. Leader in metabolic diseases and weight loss treatments, expanding aggressively into global markets.",
    financials: {
      revenue: '$17.60B (+54% YoY)',
      netProfit: 'N/A',
      cashFlow: 'Op Cash Flow $8.4B',
      period: 'Q3 2025'
    },
    indicators: {
      roic: 'High (Proprietary Growth)',
      roe: '45.2% (Estimated)',
      cashFlow: 'Robust conversion from Zepbound sales',
      debt: 'Controlled',
      currentRatio: 'Healthy',
      margin: '>50% revenue from incretin (Mounjaro $6.52B, Zepbound $3.59B)'
    },
    latestDevelopments: [
      'New factory for Orforglipron',
      'Licensing deals for oral obesity drugs'
    ],
    currentPrice: '$1085.19'
  },
  {
    symbol: 'MAR',
    fullName: 'Marriott International',
    mainBusiness: "Largest hotel chain by rooms, operating an asset-light franchise model. Extensive portfolio ranging from luxury (Ritz-Carlton) to select service brands.",
    financials: {
      revenue: '$6.49B',
      netProfit: 'Net Income $728M',
      cashFlow: 'N/A',
      period: 'Q3 2025'
    },
    indicators: {
      roic: '26.12%',
      roe: 'N/A (Asset Light)',
      cashFlow: 'Consistent stable cash generation from fees',
      debt: 'N/A',
      currentRatio: 'N/A',
      pipeline: '596,000 rooms'
    },
    latestDevelopments: [
      '100+ City Express agreements in North America'
    ],
    currentPrice: '$324.91'
  },
  {
    symbol: 'HLT',
    fullName: 'Hilton Worldwide',
    mainBusiness: "Asset-light hotel franchise, strong lifestyle and luxury brands. Focused on industry-leading unit growth and shareholder returns through buybacks.",
    financials: {
      revenue: 'N/A',
      netProfit: 'Net Income $420M',
      cashFlow: 'Op Cash Flow $816M',
      period: 'Q3 2025'
    },
    indicators: {
      roic: '32.76%',
      roe: 'High (Return to shareholders)',
      cashFlow: '$816M Operating Cash Flow (Q3 2025)',
      debt: 'N/A',
      currentRatio: '0.66',
      buyback: 'Buyback yield ~5%'
    },
    latestDevelopments: [
      '60+ new lifestyle hotels in 2026',
      'Global luxury expansions'
    ],
    currentPrice: '$298.33'
  }
];

export const ARK_HOLDER_NOTE = "As of Jan 2026, none of these stocks are core holdings in Cathie Wood's ARK funds (top holdings: TSLA, CRSP, ROKU, COIN, TEM, PLTR, etc.).";
