
import { StockData, CisLunarTier } from './types';

export const STOCKS: StockData[] = [
  {
    symbol: 'RCL',
    fullName: 'Royal Caribbean Group',
    mainBusiness: "World's second-largest cruise operator, owns Royal Caribbean International, Celebrity, Silversea; fleet 68 ships. The company focuses on large-scale innovation and luxury segments, maintaining a dominant market share in the premium vacation industry.",
    financials: {
      revenue: '$5.14B',
      netProfit: '$1.58B',
      cashFlow: 'Free Cash Flow -$989M',
      period: 'Q3 2025'
    },
    indicators: {
      occupancy: '112%',
      roic: '15.7%',
      roe: '28.4%',
      cashFlow: 'Negative FCF due to ship delivery timing',
      debt: '$20.98B',
      currentRatio: '0.16',
      leverageNote: 'highly leveraged'
    },
    latestDevelopments: [
      'Extended shipbuilding with Meyer Turku to 2036',
      'Icon 5-7 orders and options confirmed'
    ],
    currentPrice: '$304.33'
  },
  {
    symbol: 'MU',
    fullName: 'Micron Technology',
    mainBusiness: "Leading memory chip maker, focus on DRAM, NAND, HBM (High Bandwidth Memory) for AI/data centers. Micron is strategically positioned as a core infrastructure provider for the generative AI revolution.",
    financials: {
      revenue: '$13.64B (driven by HBM)',
      netProfit: '$5.24B',
      cashFlow: 'TTM Op Cash Flow Margin 53.63%',
      period: 'Q ending Nov 2025'
    },
    indicators: {
      margin: '53.63% (Op Cash Flow)',
      roic: '21.73%',
      roe: '18.9%',
      cashFlow: 'Strong Operating Cash Flow generated by HBM premium',
      debt: 'N/A',
      currentRatio: 'N/A',
      buildup: 'deliberate HBM inventory buildup'
    },
    latestDevelopments: [
      'HBM 2026 fully sold out',
      '$20B CapEx planned for FY26'
    ],
    currentPrice: '$327.02'
  },
  {
    symbol: 'LLY',
    fullName: 'Eli Lilly and Company',
    mainBusiness: "Pharma giant, incretin drugs (Mounjaro/Zepbound) dominate revenue. Leader in metabolic diseases and weight loss treatments, expanding aggressively into global markets.",
    financials: {
      revenue: '$17.60B (+54% YoY)',
      netProfit: 'N/A',
      cashFlow: 'Op Cash Flow $8.4B',
      period: 'Q3 2025'
    },
    indicators: {
      roic: 'High (Proprietary Growth)',
      roe: '45.2% (Estimated)',
      cashFlow: 'Robust conversion from Zepbound sales',
      debt: 'Controlled',
      currentRatio: 'Healthy',
      margin: '>50% revenue from incretin (Mounjaro $6.52B, Zepbound $3.59B)'
    },
    latestDevelopments: [
      'New factory for Orforglipron',
      'Licensing deals for oral obesity drugs'
    ],
    currentPrice: '$1085.19'
  },
  {
    symbol: 'MAR',
    fullName: 'Marriott International',
    mainBusiness: "Largest hotel chain by rooms, operating an asset-light franchise model. Extensive portfolio ranging from luxury (Ritz-Carlton) to select service brands.",
    financials: {
      revenue: '$6.49B',
      netProfit: 'Net Income $728M',
      cashFlow: 'N/A',
      period: 'Q3 2025'
    },
    indicators: {
      roic: '26.12%',
      roe: 'N/A (Asset Light)',
      cashFlow: 'Consistent stable cash generation from fees',
      debt: 'N/A',
      currentRatio: 'N/A',
      pipeline: '596,000 rooms'
    },
    latestDevelopments: [
      '100+ City Express agreements in North America'
    ],
    currentPrice: '$324.91'
  },
  {
    symbol: 'HLT',
    fullName: 'Hilton Worldwide',
    mainBusiness: "Asset-light hotel franchise, strong lifestyle and luxury brands. Focused on industry-leading unit growth and shareholder returns through buybacks.",
    financials: {
      revenue: 'N/A',
      netProfit: 'Net Income $420M',
      cashFlow: 'Op Cash Flow $816M',
      period: 'Q3 2025'
    },
    indicators: {
      roic: '32.76%',
      roe: 'High (Return to shareholders)',
      cashFlow: '$816M Operating Cash Flow (Q3 2025)',
      debt: 'N/A',
      currentRatio: '0.66',
      buyback: 'Buyback yield ~5%'
    },
    latestDevelopments: [
      '60+ new lifestyle hotels in 2026',
      'Global luxury expansions'
    ],
    currentPrice: '$298.33'
  }
];

export const ARK_HOLDER_NOTE = "As of Jan 2026, none of these stocks are core holdings in Cathie Wood's ARK funds (top holdings: TSLA, CRSP, ROKU, COIN, TEM, PLTR, etc.).";

// Cis-Lunar Space Economy Market Map
export const CISLUNAR_TIERS: CisLunarTier[] = [
  {
    tier: 1,
    name: 'Execution Anchors',
    riskProfile: 'Low risk',
    trl: 'TRL 9',
    characteristics: 'Proven at scale • Multi-$B backlog',
    companies: [
      {
        name: 'SpaceX',
        tier: 1,
        tierName: 'Execution Anchors',
        riskProfile: 'Low risk',
        trl: 'TRL 9',
        characteristics: 'Proven at scale • Multi-$B backlog',
        description: 'Dominant provider of Earth-to-lunar access and landing systems via Starship.',
        segment: 'Earth-to-Lunar Access'
      },
      {
        name: 'BWX Technologies',
        tier: 1,
        tierName: 'Execution Anchors',
        riskProfile: 'Low risk',
        trl: 'TRL 9',
        characteristics: 'Proven at scale • Multi-$B backlog',
        description: 'Supplies nuclear reactors and advanced power systems for lunar surface operations.',
        segment: 'Power & Energy'
      },
      {
        name: 'RTX/Collins',
        tier: 1,
        tierName: 'Execution Anchors',
        riskProfile: 'Low risk',
        trl: 'TRL 9',
        characteristics: 'Proven at scale • Multi-$B backlog',
        description: 'Delivers power, energy, thermal control, and life support systems for habitats.',
        segment: 'Power & Energy / Habitats'
      },
      {
        name: 'SpaceX Starlink',
        tier: 1,
        tierName: 'Execution Anchors',
        riskProfile: 'Low risk',
        trl: 'TRL 9',
        characteristics: 'Proven at scale • Multi-$B backlog',
        description: 'Provides cislunar communications and navigation constellation.',
        segment: 'Communications/Navigation'
      },
      {
        name: 'L3Harris',
        tier: 1,
        tierName: 'Execution Anchors',
        riskProfile: 'Low risk',
        trl: 'TRL 9',
        characteristics: 'Proven at scale • Multi-$B backlog',
        description: 'Leading supplier of communications, navigation, and PNT infrastructure.',
        segment: 'Communications/Navigation'
      },
      {
        name: 'Lockheed Martin',
        tier: 1,
        tierName: 'Execution Anchors',
        riskProfile: 'Low risk',
        trl: 'TRL 9',
        characteristics: 'Proven at scale • Multi-$B backlog',
        description: 'Develops habitats, life support, and surface construction platforms.',
        segment: 'Habitats'
      }
    ]
  },
  {
    tier: 2,
    name: 'Contracted Implementers',
    riskProfile: 'Medium risk',
    trl: 'TRL 7-9',
    characteristics: 'Contracts won • Near-term revenue',
    companies: [
      {
        name: 'Blue Origin',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'New Glenn launcher and Blue Moon lander for lunar cargo and crewed landings.',
        segment: 'Earth-to-Lunar Access'
      },
      {
        name: 'Northrop Grumman',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Lunar landers, habitats, and in-space logistics systems.',
        segment: 'Cislunar Mobility / Habitats'
      },
      {
        name: 'Firefly',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Blue Ghost lunar lander and small-to-medium launch vehicles.',
        segment: 'Earth-to-Lunar Access'
      },
      {
        name: 'Intuitive Machines',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Nova-C landers, communications relay, polar ice ISRU, and data services.',
        segment: 'Earth-to-Lunar Access / ISRU & Mining'
      },
      {
        name: 'Rocket Lab',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Electron and Neutron launch vehicles plus lunar payload delivery.',
        segment: 'Earth-to-Lunar Access'
      },
      {
        name: 'Impulse Space',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'High-performance in-space mobility and logistics vehicles (Mira/Helios).',
        segment: 'Cislunar Mobility'
      },
      {
        name: 'Redwire',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Solar arrays, power systems, and regolith processing hardware.',
        segment: 'Power & Energy / ISRU & Mining'
      },
      {
        name: 'Westinghouse',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Advanced nuclear and power systems for lunar bases.',
        segment: 'Power & Energy'
      },
      {
        name: 'Maxar/Adventure',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Robotics, power systems, and in-space manufacturing platforms.',
        segment: 'Robotics/Surface Mobility & Manufacturing'
      },
      {
        name: 'Nokia',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Lunar 4G/5G communications networks.',
        segment: 'Communications/Navigation'
      },
      {
        name: 'Axiom Space',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Commercial habitats and lunar surface infrastructure.',
        segment: 'Habitats'
      },
      {
        name: 'Sierra Space',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Inflatable LIFE habitats and Dream Chaser for lunar logistics.',
        segment: 'Habitats / Cislunar Mobility'
      },
      {
        name: 'Vast',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Commercial space stations and long-duration habitats.',
        segment: 'Habitats'
      },
      {
        name: 'Honeybee Robotics',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Robotic drills and tools for lunar ice and regolith extraction.',
        segment: 'ISRU & Mining / Robotics'
      },
      {
        name: 'General Motors',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Lunar rover development and surface mobility platforms.',
        segment: 'Robotics/Surface Mobility & Manufacturing'
      },
      {
        name: 'Venturi Astrolab',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Lunar rovers and autonomous surface mobility systems.',
        segment: 'Robotics/Surface Mobility & Manufacturing'
      },
      {
        name: 'Motiv Space Systems',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Robotic arms and mobility platforms for lunar operations.',
        segment: 'Robotics/Surface Mobility & Manufacturing'
      },
      {
        name: 'PickNik Robotics',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Advanced robotic software and manipulation systems.',
        segment: 'Robotics/Surface Mobility & Manufacturing'
      },
      {
        name: 'Tesla',
        tier: 2,
        tierName: 'Contracted Implementers',
        riskProfile: 'Medium risk',
        trl: 'TRL 7-9',
        characteristics: 'Contracts won • Near-term revenue',
        description: 'Humanoid robots and surface mobility technology for lunar manufacturing.',
        segment: 'Robotics/Surface Mobility & Manufacturing'
      }
    ]
  },
  {
    tier: 3,
    name: 'Disruptive Innovators',
    riskProfile: 'Higher risk',
    trl: 'TRL 4-7',
    characteristics: 'High asymmetric upside • Private alpha',
    companies: [
      {
        name: 'Stoke Space',
        tier: 3,
        tierName: 'Disruptive Innovators',
        riskProfile: 'Higher risk',
        trl: 'TRL 4-7',
        characteristics: 'High asymmetric upside • Private alpha',
        description: 'Fully reusable launch system for rapid, low-cost Earth-to-lunar access.',
        segment: 'Earth-to-Lunar Access'
      },
      {
        name: 'Relativity Space',
        tier: 3,
        tierName: 'Disruptive Innovators',
        riskProfile: 'Higher risk',
        trl: 'TRL 4-7',
        characteristics: 'High asymmetric upside • Private alpha',
        description: '3D-printed Terran R rockets for cost-effective lunar missions.',
        segment: 'Earth-to-Lunar Access'
      },
      {
        name: 'Portal Space',
        tier: 3,
        tierName: 'Disruptive Innovators',
        riskProfile: 'Higher risk',
        trl: 'TRL 4-7',
        characteristics: 'High asymmetric upside • Private alpha',
        description: 'Specialized cislunar mobility and logistics vehicles.',
        segment: 'Cislunar Mobility'
      },
      {
        name: 'Zeno Power',
        tier: 3,
        tierName: 'Disruptive Innovators',
        riskProfile: 'Higher risk',
        trl: 'TRL 4-7',
        characteristics: 'High asymmetric upside • Private alpha',
        description: 'Radioisotope nuclear batteries for long-duration lunar power.',
        segment: 'Power & Energy'
      },
      {
        name: 'Virtus Solis',
        tier: 3,
        tierName: 'Disruptive Innovators',
        riskProfile: 'Higher risk',
        trl: 'TRL 4-7',
        characteristics: 'High asymmetric upside • Private alpha',
        description: 'Space-based solar power systems for continuous cislunar energy.',
        segment: 'Power & Energy'
      },
      {
        name: 'Interlune',
        tier: 3,
        tierName: 'Disruptive Innovators',
        riskProfile: 'Higher risk',
        trl: 'TRL 4-7',
        characteristics: 'High asymmetric upside • Private alpha',
        description: 'Helium-3 mining for fusion and quantum computing applications.',
        segment: 'ISRU & Mining'
      },
      {
        name: 'Helios',
        tier: 3,
        tierName: 'Disruptive Innovators',
        riskProfile: 'Higher risk',
        trl: 'TRL 4-7',
        characteristics: 'High asymmetric upside • Private alpha',
        description: 'Molten Regolith Electrolysis for oxygen and metal extraction from lunar soil.',
        segment: 'ISRU & Mining'
      },
      {
        name: 'Lunar Outpost',
        tier: 3,
        tierName: 'Disruptive Innovators',
        riskProfile: 'Higher risk',
        trl: 'TRL 4-7',
        characteristics: 'High asymmetric upside • Private alpha',
        description: 'Autonomous rovers and robotic mining platforms.',
        segment: 'Robotics/Surface Mobility & Manufacturing / ISRU & Mining'
      },
      {
        name: 'OffWorld',
        tier: 3,
        tierName: 'Disruptive Innovators',
        riskProfile: 'Higher risk',
        trl: 'TRL 4-7',
        characteristics: 'High asymmetric upside • Private alpha',
        description: 'Industrial-scale robotic mining systems for lunar resources.',
        segment: 'Robotics/Surface Mobility & Manufacturing / ISRU & Mining'
      },
      {
        name: 'GITAI',
        tier: 3,
        tierName: 'Disruptive Innovators',
        riskProfile: 'Higher risk',
        trl: 'TRL 4-7',
        characteristics: 'High asymmetric upside • Private alpha',
        description: 'General-purpose humanoid and robotic systems for in-space assembly.',
        segment: 'Robotics/Surface Mobility & Manufacturing'
      }
    ]
  }
];

// Quick lookup by company name
export const CISLUNAR_COMPANIES_MAP = new Map(
  CISLUNAR_TIERS.flatMap(tier => 
    tier.companies.map(company => [company.name, company])
  )
);
